services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # Optional: You can remove these limits if you want Mongo to use all available CPU
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 6G

volumes:
  mongo_data:
